name: freelance_time_controller_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  args: ^2.0.0
  dotenv: ^4.0.1
  dart_dotenv: ^1.0.1
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_router_generator: ^1.0.2
  crypto: ^3.0.2
  sembast: ^3.2.0
  uuid: ^3.0.6
  shelf_test_handler: ^2.0.0
  
  

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  build_runner: ^2.1.10
  test: ^1.15.0
